-- TABLE tMembres;
TABLE tMembres;
-- TABLE tJoueurs;
TABLE tJoueurs;
-- TABLE tCartes;
TABLE tCartes;
-- TABLE tCartesInvention;
TABLE tCartesInvention;
-- TABLE tCartesRessource;
TABLE tCartesRessource;
-- TABLE tCartesEffet;
TABLE tCartesEffet;
-- TABLE tFacultes;
TABLE tFacultes;
-- TABLE tTournois;
TABLE tTournois;
-- TABLE tOrganisateurs;
TABLE tOrganisateurs;
-- TABLE tMatchs;
TABLE tMatchs;
-- TABLE tParticipations;
TABLE tParticipations;
-- TABLE tDecks;
TABLE tDecks;
