INSERT INTO tcartes (nom,extensionsts) VALUES ('Cyprus','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Guinea-bissau','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Albania','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bosnia and Herzegovina','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Northern Mariana Islands','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Maldives','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Paraguay','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Netherlands Antilles','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Malaysia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Rwanda','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Lebanon','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bahamas','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Estonia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Mozambique','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Mauritania','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bahrain','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Zimbabwe','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Western Sahara','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Philippines','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Saint Helena','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Turks and Caicos Islands','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Guadeloupe','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Mozambique','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('San Marino','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Norway','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('El Salvador','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Guinea','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Maldives','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Mayotte','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Ireland','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Zimbabwe','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sierra Leone','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sierra Leone','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Afghanistan','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Tunisia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Kiribati','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Mali','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Myanmar','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Belize','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bangladesh','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Grenada','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Micronesia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bulgaria','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Netherlands Antilles','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Chile','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Peru','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Paraguay','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Chile','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Panama','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Hungary','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Uganda','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Namibia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Saint Lucia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Malaysia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Haiti','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Iran','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sierra Leone','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Saint Helena','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Vanuatu','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Guatemala','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Central African Republic','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Uzbekistan','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Cape Verde','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Virgin Islands, British','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Vanuatu','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bahrain','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Israel','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Libyan Arab Jamahiriya','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Palau','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Macedonia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Micronesia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Anguilla','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bermuda','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Poland','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Niue','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Falkland Islands (Malvinas)','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Indonesia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Grenada','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Kiribati','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Bermuda','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Saint Kitts and Nevis','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Honduras','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Poland','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Liechtenstein','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Tuvalu','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Belize','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Tuvalu','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Puerto Rico','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sudan','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Thailand','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Belgium','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Algeria','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sudan','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Dominican Republic','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Western Sahara','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Sierra Leone','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Gambia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Indonesia','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('France','l assemblée');
INSERT INTO tcartes (nom,extensionsts) VALUES ('Zimbabwe','l assemblée');
