-- insertion_decks

INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','China');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Gambia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','South Georgia and The South Sandwich Islands');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Estonia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Colombia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Denmark');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Pakistan');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Puerto Rico');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Uganda');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Jamaica');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cook Islands');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Kyrgyzstan');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cuba');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Comoros');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Namibia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Samoa');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Marshall Islands');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Botswana');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Armenia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Equatorial Guinea');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Netherlands Antilles');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Wallis and Futuna');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Indonesia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Holy See (Vatican City State)');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Morocco');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Ethiopia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Indonesia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Argentina');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Malaysia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Martinique');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cape Verde');

INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Portugal');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Tajikistan');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Yemen');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Zambia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Bangladesh');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cyprus');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Oman');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Seychelles');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cameroon');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Bolivia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Albania');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','New Zealand');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Germany');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Congo');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Dominican Republic');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Bermuda');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Saint Pierre and Miquelon');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Guatemala');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Burkina Faso');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Angola');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Yemen');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Brazil');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Jamaica');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Haiti');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Puerto Rico');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Puerto Rico');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Seychelles');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Saint Pierre and Miquelon');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Ecuador');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Grenada');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Turks and Caicos Islands');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Virgin Islands, British');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Cyprus');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Turkey');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Venezuela');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','France');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Bulgaria');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','New Caledonia');
INSERT INTO tdecks (login,annee,nom) VALUES ('lemairepierre','1999','Benin');